change about section
fiquell/deoxa pull request #1
Opened 2023-10-18 17:06 UTC by izmahaerill

...

2023-10-18 17:14 UTC, fiquell requested changes
Please change all tag!

NOTE:
- Remove all text colors

2023-10-18 17:18 UTC, fiquell commented on src/components/About.tsx
> +            <Typography variant="h3" className="pb-5">
Use `mb-3` for consistent code!

2023-10-18 17:19 UTC, fiquell commented on src/components/About.tsx
> +          <div className="container grid lg:grid-cols-3 place-items-center grid-cols-1 gap-5">
Use `md:grid-cols-3` for medium devices

2023-10-18 17:21 UTC, fiquell commented on src/components/About.tsx
> +            <Typography variant="paragraph" className="lg:w-1/2 text-gray-500 text-center">
Remove `text-gray-500`

2023-10-18 17:23 UTC, fiquell commented on src/components/About.tsx
> +              <Typography variant="paragraph" className="text-xl mb-2">Lorem, ipsum </Typography>
Use `h4`/`h5`/`h6`

2023-10-18 17:23 UTC, fiquell commented on src/components/About.tsx
> +              <Typography variant="paragraph" className="text-xl">Lorem, ipsum</Typography>
Use `h4`/`h5`/`h6`

2023-10-18 21:01 UTC, fiquell requested changes
Improve this code!..

2023-10-18 21:05 UTC, fiquell commented on src/components/About.tsx
> +      <div className="pt-12">
Remove `pt-12` and use `mt-32`

2023-10-19 15:52 UTC, izmahaerill commented on src/components/About.tsx
> +export default function About() {
it's error when use it

2023-10-20 16:26 UTC, merged